version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    working_directory: ~/aws-typescript-lambda-boilerplate
    executor: node/default
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          app-dir: ~/aws-typescript-lambda-boilerplate
          cache-path: node_modules
          override-ci-command: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:current
    steps:
      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: test-results.xml
          destination: deliverable.xml
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
