version: 2.1

orbs:
  node: circleci/node@5.0.1
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/aws-typescript-lambda-boilerplate
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14'
      - node/install-packages:
          app-dir: ~/aws-typescript-lambda-boilerplate
          cache-path: node_modules
          override-ci-command: yarn
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: reports/junit/test-results.xml
          destination: deliverable.xml
      - store_artifacts:
          path: coverage
          destination: coverage
      - codecov/upload:
          file: coverage/coverage-final.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
