AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "aws-typescript-lambda-boilerplate"

Globals:
  Function:
    Timeout: 15

Parameters:
  Stage:
    Description: Environment variable when deploying to production
    Type: String
    Default: prod

Resources:
  pingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        Ping:
          Type: Api
          Properties:
            Path: /ping
            Method: get

Outputs:
  PingApi:
    Description: "API gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping/"
  pingFunction:
    Description: "Ping function ARN"
    Value: !GetAtt pingFunction.Arn
  pingFunctionIamRole:
    Description: "IAM role for the function"
    Value: !GetAtt pingFunctionRole.Arn
